### PR TITLE
switch from Travis CI to GitHub Actions CI 💚

### PR DESCRIPTION
**Pull request by derhuerst**
follow-up of #41

@ kamalmostafa Do you know why `make` fails under MacOS?

### CODE REVIEW

**Comment by kamalmostafa** [comment]
> @ kamalmostafa Do you know why `make` fails under MacOS?

Looks like MacOS doesn't support the libsndio backend.  I expect that adding "--without-sndio" to your macos ./configure step will fix it.  I'll let your verify that, and will stand by for an updated PR.  Thanks!

**Comment by derhuerst** [comment]
> Looks like MacOS doesn't support the libsndio backend.

It worked on Travis CI before though. 🤔

**Comment by kamalmostafa** [comment]
> > Looks like MacOS doesn't support the libsndio backend.
> 
> It worked on Travis CI before though.

The libsndio backend was just committed to minimodem quite recently -- more recently than your earlier Travis CI testing, I think.  When I committed it, I did wonder if it might break a MacOS build.  Now we know!  :-)

**Comment by kamalmostafa** [comment]
Oh @derhuerst also ...  The `minimodem --benchmarks` step doesn't hurt anything, but isn't really relevant to the "build process"...  However `make check` does run a bunch of "required-to-pass" self tests.  How about adding a `make check` as a build step (or a post-build step or whatever is right)?

**Comment by kamalmostafa** [comment]
Very good!  Thanks again for doing this, @derhuerst.  Your diligence is much appreciated.

**Pull request merged**
